FROM python:3
MAINTAINER Kerem Bilgicer <krmbil@gmail.com>
EXPOSE 5000
ADD /mqttapi/requirements.txt /
ADD /mqttapi/dbmanager.py /
ADD /mqttapi/hashing_passwords.py /
ADD /mqttapi/Model.py /
ADD /mqttapi/pbkdf2.py /
ADD /mqttapi/UserApi.py /
RUN pip install -U -r requirements.txt 
CMD [ "python", "./UserApi.py" ]